# Generated by Django 4.1.7 on 2023-03-14 17:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_menu_delete_pages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="content",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
