# Generated by Django 4.1.7 on 2023-03-14 17:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_menu_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="content_upload",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
