# Generated by Django 4.1.7 on 2023-03-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_menu_content_upload_alter_menu_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="snippet",
            field=models.CharField(
                default="Click Link to View More...", max_length=255
            ),
        ),
    ]
