# Generated by Django 4.1.7 on 2023-03-21 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_service_card_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="card_number",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(3)]
            ),
        ),
    ]
