# Generated by Django 4.1.7 on 2023-03-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="address",
            field=models.CharField(default="address", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.CharField(default="email", max_length=255),
        ),
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(default="9999999999", max_length=50),
        ),
    ]
