# Generated by Django 4.1.7 on 2023-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_contact_address_contact_email_contact_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="business_hours",
            field=models.CharField(default="Mon-Friday", max_length=150),
        ),
        migrations.AddField(
            model_name="contact",
            name="service_area",
            field=models.CharField(default="Denver Metropolitan Area", max_length=150),
        ),
        migrations.AlterField(
            model_name="contact",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact", name="email", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="contact", name="slug", field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="service", name="slug", field=models.SlugField(unique=True),
        ),
    ]
