# Generated by Django 4.1.7 on 2023-03-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_contact_business_hours_contact_service_area_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="about", name="slug", field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="contact", name="business_hours", field=models.TextField(),
        ),
    ]
